/* eslint-disable */
import * as types from './graphql';
import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';

/**
 * Map of all GraphQL operations in the project.
 *
 * This map has several performance disadvantages:
 * 1. It is not tree-shakeable, so it will include all operations in the project.
 * 2. It is not minifiable, so the string of a GraphQL query will be multiple times inside the bundle.
 * 3. It does not support dead code elimination, so it will add unused operations.
 *
 * Therefore it is highly recommended to use the babel or swc plugin for production.
 * Learn more about it here: https://the-guild.dev/graphql/codegen/plugins/presets/preset-client#reducing-bundle-size
 */
type Documents = {
    "\n  query AuthBootMe {\n    me {\n      id\n      email\n      firstName\n      lastName\n      fullName\n      roleId\n      roleCode\n      roleName\n      isActive\n      permissions\n      createdAt\n      updatedAt\n    }\n  }\n": typeof types.AuthBootMeDocument,
    "\n  mutation Logout($refreshToken: String!) {\n    logout(refreshToken: $refreshToken)\n  }\n": typeof types.LogoutDocument,
    "\n  mutation Login(\n    $emailOrEmployeeNumber: String!\n    $password: String!\n    $rememberMe: Boolean\n  ) {\n    login(\n      emailOrEmployeeNumber: $emailOrEmployeeNumber\n      password: $password\n      rememberMe: $rememberMe\n    ) {\n      accessToken\n      refreshToken\n    }\n  }\n": typeof types.LoginDocument,
    "\n  mutation SignUp(\n    $firstName: String!\n    $lastName: String!\n    $email: String!\n    $password: String!\n    $rememberMe: Boolean\n  ) {\n    signUp(\n      firstName: $firstName\n      lastName: $lastName\n      email: $email\n      password: $password\n      rememberMe: $rememberMe\n    ) {\n      accessToken\n      refreshToken\n    }\n  }\n": typeof types.SignUpDocument,
    "\n  query DashboardOverview {\n    getDashboard {\n      kpis {\n        key\n        title\n        subtitle\n        value\n        tone\n      }\n      recentUsers {\n        id\n        email\n        firstName\n        lastName\n        roleName\n        isActive\n        createdAt\n      }\n      projectCards {\n        id\n        name\n        status\n        progressPercent\n        memberCount\n      }\n      myTasks {\n        id\n        title\n        projectId\n        projectName\n        status\n        progress\n        priority\n        dueDate\n      }\n    }\n  }\n": typeof types.DashboardOverviewDocument,
    "\n  query ProjectDetail($id: ID!) {\n    getProject(id: $id) {\n      id\n      name\n      description\n      status\n      progressPercent\n      memberCount\n      myPermissions\n      myRoleName\n      myRoleCode\n      createdAt\n      updatedAt\n    }\n  }\n": typeof types.ProjectDetailDocument,
    "\n  query ProjectTasks($page: Int, $limit: Int, $filters: TaskFilterInputType) {\n    getTasks(page: $page, limit: $limit, filters: $filters) {\n      nodes {\n        id\n        title\n        description\n        type\n        weight\n        progress\n        status\n        priority\n        dueDate\n        projectId\n        assignees {\n          id\n          userId\n          user {\n            id\n            fullName\n            email\n          }\n        }\n      }\n      pageInfo {\n        totalCount\n      }\n    }\n  }\n": typeof types.ProjectTasksDocument,
    "\n  query ProjectMembers($projectId: ID!) {\n    getProjectMembers(projectId: $projectId) {\n      nodes {\n        id\n        userId\n        firstName\n        lastName\n        email\n        fullName\n        roleId\n        roleCode\n        roleName\n        joinedAt\n      }\n    }\n  }\n": typeof types.ProjectMembersDocument,
    "\n  query TaskDetail($id: ID!) {\n    getTask(id: $id) {\n      id\n      title\n      description\n      type\n      weight\n      progress\n      status\n      priority\n      dueDate\n      projectId\n      subtasks {\n        id\n        title\n        weight\n        isComplete\n      }\n      assignees {\n        id\n        userId\n        user {\n          id\n          fullName\n          email\n        }\n      }\n    }\n  }\n": typeof types.TaskDetailDocument,
    "\n  mutation CreateTask(\n    $projectId: ID!\n    $title: String!\n    $description: String\n    $type: TaskTypeEnumType\n    $weight: Int!\n    $priority: TaskPriorityEnumType\n    $dueDate: DateTime\n  ) {\n    createTask(\n      projectId: $projectId\n      title: $title\n      description: $description\n      type: $type\n      weight: $weight\n      priority: $priority\n      dueDate: $dueDate\n    ) {\n      id\n    }\n  }\n": typeof types.CreateTaskDocument,
    "\n  mutation UpdateTask($id: ID!, $status: TaskStatusEnumType, $progress: Int) {\n    updateTask(id: $id, status: $status, progress: $progress) {\n      id\n      status\n      progress\n    }\n  }\n": typeof types.UpdateTaskDocument,
    "\n  mutation AddProjectMember($projectId: ID!, $memberUserId: ID!, $roleId: ID!) {\n    addProjectMember(projectId: $projectId, memberUserId: $memberUserId, roleId: $roleId) {\n      id\n    }\n  }\n": typeof types.AddProjectMemberDocument,
    "\n  mutation UpdateProject($id: ID!, $name: String, $description: String, $status: ProjectStatusEnumType) {\n    updateProject(id: $id, name: $name, description: $description, status: $status) {\n      id\n      name\n      description\n      status\n    }\n  }\n": typeof types.UpdateProjectDocument,
    "\n  mutation CreateSubtask($taskId: ID!, $title: String!, $weight: Int!) {\n    createSubtask(taskId: $taskId, title: $title, weight: $weight) {\n      id\n      subtasks {\n        id\n        title\n        weight\n        isComplete\n      }\n    }\n  }\n": typeof types.CreateSubtaskDocument,
    "\n  mutation UpdateSubtask($id: ID!, $isComplete: Boolean, $weight: Int) {\n    updateSubtask(id: $id, isComplete: $isComplete, weight: $weight) {\n      id\n      subtasks {\n        id\n        title\n        weight\n        isComplete\n      }\n    }\n  }\n": typeof types.UpdateSubtaskDocument,
    "\n  query ProjectRoles($limit: Int) {\n    getRoles(limit: $limit) {\n      nodes {\n        id\n        code\n        name\n      }\n    }\n  }\n": typeof types.ProjectRolesDocument,
    "\n  query ProjectUsers($limit: Int, $filters: UserFilterInputType) {\n    getUsers(limit: $limit, filters: $filters) {\n      nodes {\n        id\n        fullName\n        email\n      }\n    }\n  }\n": typeof types.ProjectUsersDocument,
    "\n  query Projects($page: Int, $limit: Int, $filters: ProjectFilterInputType) {\n    getProjects(page: $page, limit: $limit, filters: $filters) {\n      nodes {\n        id\n        name\n        description\n        status\n        progressPercent\n        memberCount\n        createdAt\n        updatedAt\n      }\n      pageInfo {\n        isFirstPage\n        isLastPage\n        currentPage\n        previousPage\n        nextPage\n        pageCount\n        totalCount\n      }\n    }\n  }\n": typeof types.ProjectsDocument,
    "\n  mutation CreateProject($name: String!, $description: String) {\n    createProject(name: $name, description: $description) {\n      id\n      name\n    }\n  }\n": typeof types.CreateProjectDocument,
    "\n  query Me {\n    me {\n      id\n      email\n      firstName\n      lastName\n      roleName\n      sessions {\n        nodes {\n          id\n          expiresAt\n          userAgent\n          ipAddress\n          revoked\n          revokedAt\n          createdAt\n        }\n        pageInfo {\n          totalCount\n        }\n      }\n    }\n  }\n": typeof types.MeDocument,
    "\n  mutation UpdateUser($firstName: String, $lastName: String, $email: String) {\n    updateUser(firstName: $firstName, lastName: $lastName, email: $email) {\n      id\n    }\n  }\n": typeof types.UpdateUserDocument,
    "\n  mutation CreateRole(\n    $name: String!\n    $code: String!\n    $description: String\n    $permissionCodes: [PermissionEnumType!]!\n  ) {\n    createRole(\n      name: $name\n      code: $code\n      description: $description\n      permissionCodes: $permissionCodes\n    ) {\n      id\n    }\n  }\n": typeof types.CreateRoleDocument,
    "\n  query Role($id: ID!) {\n    getRole(id: $id) {\n      id\n      code\n      name\n      description\n      permissions\n    }\n  }\n": typeof types.RoleDocument,
    "\n  mutation UpdateRole(\n    $id: ID!\n    $name: String\n    $description: String\n    $permissionCodes: [PermissionEnumType!]\n  ) {\n    updateRole(\n      id: $id\n      name: $name\n      description: $description\n      permissionCodes: $permissionCodes\n    ) {\n      id\n    }\n  }\n": typeof types.UpdateRoleDocument,
    "\n  query Roles($page: Int, $limit: Int, $filters: RoleFilterInputType) {\n    getRoles(page: $page, limit: $limit, filters: $filters) {\n      nodes {\n        id\n        code\n        name\n        description\n        createdAt\n      }\n      pageInfo {\n        isFirstPage\n        isLastPage\n        currentPage\n        previousPage\n        nextPage\n        pageCount\n        totalCount\n      }\n    }\n  }\n": typeof types.RolesDocument,
    "\n  query Users($page: Int, $limit: Int, $filters: UserFilterInputType) {\n    getUsers(page: $page, limit: $limit, filters: $filters) {\n      nodes {\n        id\n        email\n        firstName\n        lastName\n        fullName\n        roleName\n        roleCode\n        isActive\n        createdAt\n      }\n      pageInfo {\n        isFirstPage\n        isLastPage\n        currentPage\n        previousPage\n        nextPage\n        pageCount\n        totalCount\n      }\n    }\n  }\n": typeof types.UsersDocument,
    "\n  mutation RefreshToken($refreshToken: String!) {\n    refreshToken(refreshToken: $refreshToken) {\n      accessToken\n      refreshToken\n    }\n  }\n": typeof types.RefreshTokenDocument,
};
const documents: Documents = {
    "\n  query AuthBootMe {\n    me {\n      id\n      email\n      firstName\n      lastName\n      fullName\n      roleId\n      roleCode\n      roleName\n      isActive\n      permissions\n      createdAt\n      updatedAt\n    }\n  }\n": types.AuthBootMeDocument,
    "\n  mutation Logout($refreshToken: String!) {\n    logout(refreshToken: $refreshToken)\n  }\n": types.LogoutDocument,
    "\n  mutation Login(\n    $emailOrEmployeeNumber: String!\n    $password: String!\n    $rememberMe: Boolean\n  ) {\n    login(\n      emailOrEmployeeNumber: $emailOrEmployeeNumber\n      password: $password\n      rememberMe: $rememberMe\n    ) {\n      accessToken\n      refreshToken\n    }\n  }\n": types.LoginDocument,
    "\n  mutation SignUp(\n    $firstName: String!\n    $lastName: String!\n    $email: String!\n    $password: String!\n    $rememberMe: Boolean\n  ) {\n    signUp(\n      firstName: $firstName\n      lastName: $lastName\n      email: $email\n      password: $password\n      rememberMe: $rememberMe\n    ) {\n      accessToken\n      refreshToken\n    }\n  }\n": types.SignUpDocument,
    "\n  query DashboardOverview {\n    getDashboard {\n      kpis {\n        key\n        title\n        subtitle\n        value\n        tone\n      }\n      recentUsers {\n        id\n        email\n        firstName\n        lastName\n        roleName\n        isActive\n        createdAt\n      }\n      projectCards {\n        id\n        name\n        status\n        progressPercent\n        memberCount\n      }\n      myTasks {\n        id\n        title\n        projectId\n        projectName\n        status\n        progress\n        priority\n        dueDate\n      }\n    }\n  }\n": types.DashboardOverviewDocument,
    "\n  query ProjectDetail($id: ID!) {\n    getProject(id: $id) {\n      id\n      name\n      description\n      status\n      progressPercent\n      memberCount\n      myPermissions\n      myRoleName\n      myRoleCode\n      createdAt\n      updatedAt\n    }\n  }\n": types.ProjectDetailDocument,
    "\n  query ProjectTasks($page: Int, $limit: Int, $filters: TaskFilterInputType) {\n    getTasks(page: $page, limit: $limit, filters: $filters) {\n      nodes {\n        id\n        title\n        description\n        type\n        weight\n        progress\n        status\n        priority\n        dueDate\n        projectId\n        assignees {\n          id\n          userId\n          user {\n            id\n            fullName\n            email\n          }\n        }\n      }\n      pageInfo {\n        totalCount\n      }\n    }\n  }\n": types.ProjectTasksDocument,
    "\n  query ProjectMembers($projectId: ID!) {\n    getProjectMembers(projectId: $projectId) {\n      nodes {\n        id\n        userId\n        firstName\n        lastName\n        email\n        fullName\n        roleId\n        roleCode\n        roleName\n        joinedAt\n      }\n    }\n  }\n": types.ProjectMembersDocument,
    "\n  query TaskDetail($id: ID!) {\n    getTask(id: $id) {\n      id\n      title\n      description\n      type\n      weight\n      progress\n      status\n      priority\n      dueDate\n      projectId\n      subtasks {\n        id\n        title\n        weight\n        isComplete\n      }\n      assignees {\n        id\n        userId\n        user {\n          id\n          fullName\n          email\n        }\n      }\n    }\n  }\n": types.TaskDetailDocument,
    "\n  mutation CreateTask(\n    $projectId: ID!\n    $title: String!\n    $description: String\n    $type: TaskTypeEnumType\n    $weight: Int!\n    $priority: TaskPriorityEnumType\n    $dueDate: DateTime\n  ) {\n    createTask(\n      projectId: $projectId\n      title: $title\n      description: $description\n      type: $type\n      weight: $weight\n      priority: $priority\n      dueDate: $dueDate\n    ) {\n      id\n    }\n  }\n": types.CreateTaskDocument,
    "\n  mutation UpdateTask($id: ID!, $status: TaskStatusEnumType, $progress: Int) {\n    updateTask(id: $id, status: $status, progress: $progress) {\n      id\n      status\n      progress\n    }\n  }\n": types.UpdateTaskDocument,
    "\n  mutation AddProjectMember($projectId: ID!, $memberUserId: ID!, $roleId: ID!) {\n    addProjectMember(projectId: $projectId, memberUserId: $memberUserId, roleId: $roleId) {\n      id\n    }\n  }\n": types.AddProjectMemberDocument,
    "\n  mutation UpdateProject($id: ID!, $name: String, $description: String, $status: ProjectStatusEnumType) {\n    updateProject(id: $id, name: $name, description: $description, status: $status) {\n      id\n      name\n      description\n      status\n    }\n  }\n": types.UpdateProjectDocument,
    "\n  mutation CreateSubtask($taskId: ID!, $title: String!, $weight: Int!) {\n    createSubtask(taskId: $taskId, title: $title, weight: $weight) {\n      id\n      subtasks {\n        id\n        title\n        weight\n        isComplete\n      }\n    }\n  }\n": types.CreateSubtaskDocument,
    "\n  mutation UpdateSubtask($id: ID!, $isComplete: Boolean, $weight: Int) {\n    updateSubtask(id: $id, isComplete: $isComplete, weight: $weight) {\n      id\n      subtasks {\n        id\n        title\n        weight\n        isComplete\n      }\n    }\n  }\n": types.UpdateSubtaskDocument,
    "\n  query ProjectRoles($limit: Int) {\n    getRoles(limit: $limit) {\n      nodes {\n        id\n        code\n        name\n      }\n    }\n  }\n": types.ProjectRolesDocument,
    "\n  query ProjectUsers($limit: Int, $filters: UserFilterInputType) {\n    getUsers(limit: $limit, filters: $filters) {\n      nodes {\n        id\n        fullName\n        email\n      }\n    }\n  }\n": types.ProjectUsersDocument,
    "\n  query Projects($page: Int, $limit: Int, $filters: ProjectFilterInputType) {\n    getProjects(page: $page, limit: $limit, filters: $filters) {\n      nodes {\n        id\n        name\n        description\n        status\n        progressPercent\n        memberCount\n        createdAt\n        updatedAt\n      }\n      pageInfo {\n        isFirstPage\n        isLastPage\n        currentPage\n        previousPage\n        nextPage\n        pageCount\n        totalCount\n      }\n    }\n  }\n": types.ProjectsDocument,
    "\n  mutation CreateProject($name: String!, $description: String) {\n    createProject(name: $name, description: $description) {\n      id\n      name\n    }\n  }\n": types.CreateProjectDocument,
    "\n  query Me {\n    me {\n      id\n      email\n      firstName\n      lastName\n      roleName\n      sessions {\n        nodes {\n          id\n          expiresAt\n          userAgent\n          ipAddress\n          revoked\n          revokedAt\n          createdAt\n        }\n        pageInfo {\n          totalCount\n        }\n      }\n    }\n  }\n": types.MeDocument,
    "\n  mutation UpdateUser($firstName: String, $lastName: String, $email: String) {\n    updateUser(firstName: $firstName, lastName: $lastName, email: $email) {\n      id\n    }\n  }\n": types.UpdateUserDocument,
    "\n  mutation CreateRole(\n    $name: String!\n    $code: String!\n    $description: String\n    $permissionCodes: [PermissionEnumType!]!\n  ) {\n    createRole(\n      name: $name\n      code: $code\n      description: $description\n      permissionCodes: $permissionCodes\n    ) {\n      id\n    }\n  }\n": types.CreateRoleDocument,
    "\n  query Role($id: ID!) {\n    getRole(id: $id) {\n      id\n      code\n      name\n      description\n      permissions\n    }\n  }\n": types.RoleDocument,
    "\n  mutation UpdateRole(\n    $id: ID!\n    $name: String\n    $description: String\n    $permissionCodes: [PermissionEnumType!]\n  ) {\n    updateRole(\n      id: $id\n      name: $name\n      description: $description\n      permissionCodes: $permissionCodes\n    ) {\n      id\n    }\n  }\n": types.UpdateRoleDocument,
    "\n  query Roles($page: Int, $limit: Int, $filters: RoleFilterInputType) {\n    getRoles(page: $page, limit: $limit, filters: $filters) {\n      nodes {\n        id\n        code\n        name\n        description\n        createdAt\n      }\n      pageInfo {\n        isFirstPage\n        isLastPage\n        currentPage\n        previousPage\n        nextPage\n        pageCount\n        totalCount\n      }\n    }\n  }\n": types.RolesDocument,
    "\n  query Users($page: Int, $limit: Int, $filters: UserFilterInputType) {\n    getUsers(page: $page, limit: $limit, filters: $filters) {\n      nodes {\n        id\n        email\n        firstName\n        lastName\n        fullName\n        roleName\n        roleCode\n        isActive\n        createdAt\n      }\n      pageInfo {\n        isFirstPage\n        isLastPage\n        currentPage\n        previousPage\n        nextPage\n        pageCount\n        totalCount\n      }\n    }\n  }\n": types.UsersDocument,
    "\n  mutation RefreshToken($refreshToken: String!) {\n    refreshToken(refreshToken: $refreshToken) {\n      accessToken\n      refreshToken\n    }\n  }\n": types.RefreshTokenDocument,
};

/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 *
 *
 * @example
 * ```ts
 * const query = gql(`query GetUser($id: ID!) { user(id: $id) { name } }`);
 * ```
 *
 * The query argument is unknown!
 * Please regenerate the types.
 */
export function gql(source: string): unknown;

/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query AuthBootMe {\n    me {\n      id\n      email\n      firstName\n      lastName\n      fullName\n      roleId\n      roleCode\n      roleName\n      isActive\n      permissions\n      createdAt\n      updatedAt\n    }\n  }\n"): (typeof documents)["\n  query AuthBootMe {\n    me {\n      id\n      email\n      firstName\n      lastName\n      fullName\n      roleId\n      roleCode\n      roleName\n      isActive\n      permissions\n      createdAt\n      updatedAt\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  mutation Logout($refreshToken: String!) {\n    logout(refreshToken: $refreshToken)\n  }\n"): (typeof documents)["\n  mutation Logout($refreshToken: String!) {\n    logout(refreshToken: $refreshToken)\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  mutation Login(\n    $emailOrEmployeeNumber: String!\n    $password: String!\n    $rememberMe: Boolean\n  ) {\n    login(\n      emailOrEmployeeNumber: $emailOrEmployeeNumber\n      password: $password\n      rememberMe: $rememberMe\n    ) {\n      accessToken\n      refreshToken\n    }\n  }\n"): (typeof documents)["\n  mutation Login(\n    $emailOrEmployeeNumber: String!\n    $password: String!\n    $rememberMe: Boolean\n  ) {\n    login(\n      emailOrEmployeeNumber: $emailOrEmployeeNumber\n      password: $password\n      rememberMe: $rememberMe\n    ) {\n      accessToken\n      refreshToken\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  mutation SignUp(\n    $firstName: String!\n    $lastName: String!\n    $email: String!\n    $password: String!\n    $rememberMe: Boolean\n  ) {\n    signUp(\n      firstName: $firstName\n      lastName: $lastName\n      email: $email\n      password: $password\n      rememberMe: $rememberMe\n    ) {\n      accessToken\n      refreshToken\n    }\n  }\n"): (typeof documents)["\n  mutation SignUp(\n    $firstName: String!\n    $lastName: String!\n    $email: String!\n    $password: String!\n    $rememberMe: Boolean\n  ) {\n    signUp(\n      firstName: $firstName\n      lastName: $lastName\n      email: $email\n      password: $password\n      rememberMe: $rememberMe\n    ) {\n      accessToken\n      refreshToken\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query DashboardOverview {\n    getDashboard {\n      kpis {\n        key\n        title\n        subtitle\n        value\n        tone\n      }\n      recentUsers {\n        id\n        email\n        firstName\n        lastName\n        roleName\n        isActive\n        createdAt\n      }\n      projectCards {\n        id\n        name\n        status\n        progressPercent\n        memberCount\n      }\n      myTasks {\n        id\n        title\n        projectId\n        projectName\n        status\n        progress\n        priority\n        dueDate\n      }\n    }\n  }\n"): (typeof documents)["\n  query DashboardOverview {\n    getDashboard {\n      kpis {\n        key\n        title\n        subtitle\n        value\n        tone\n      }\n      recentUsers {\n        id\n        email\n        firstName\n        lastName\n        roleName\n        isActive\n        createdAt\n      }\n      projectCards {\n        id\n        name\n        status\n        progressPercent\n        memberCount\n      }\n      myTasks {\n        id\n        title\n        projectId\n        projectName\n        status\n        progress\n        priority\n        dueDate\n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query ProjectDetail($id: ID!) {\n    getProject(id: $id) {\n      id\n      name\n      description\n      status\n      progressPercent\n      memberCount\n      myPermissions\n      myRoleName\n      myRoleCode\n      createdAt\n      updatedAt\n    }\n  }\n"): (typeof documents)["\n  query ProjectDetail($id: ID!) {\n    getProject(id: $id) {\n      id\n      name\n      description\n      status\n      progressPercent\n      memberCount\n      myPermissions\n      myRoleName\n      myRoleCode\n      createdAt\n      updatedAt\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query ProjectTasks($page: Int, $limit: Int, $filters: TaskFilterInputType) {\n    getTasks(page: $page, limit: $limit, filters: $filters) {\n      nodes {\n        id\n        title\n        description\n        type\n        weight\n        progress\n        status\n        priority\n        dueDate\n        projectId\n        assignees {\n          id\n          userId\n          user {\n            id\n            fullName\n            email\n          }\n        }\n      }\n      pageInfo {\n        totalCount\n      }\n    }\n  }\n"): (typeof documents)["\n  query ProjectTasks($page: Int, $limit: Int, $filters: TaskFilterInputType) {\n    getTasks(page: $page, limit: $limit, filters: $filters) {\n      nodes {\n        id\n        title\n        description\n        type\n        weight\n        progress\n        status\n        priority\n        dueDate\n        projectId\n        assignees {\n          id\n          userId\n          user {\n            id\n            fullName\n            email\n          }\n        }\n      }\n      pageInfo {\n        totalCount\n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query ProjectMembers($projectId: ID!) {\n    getProjectMembers(projectId: $projectId) {\n      nodes {\n        id\n        userId\n        firstName\n        lastName\n        email\n        fullName\n        roleId\n        roleCode\n        roleName\n        joinedAt\n      }\n    }\n  }\n"): (typeof documents)["\n  query ProjectMembers($projectId: ID!) {\n    getProjectMembers(projectId: $projectId) {\n      nodes {\n        id\n        userId\n        firstName\n        lastName\n        email\n        fullName\n        roleId\n        roleCode\n        roleName\n        joinedAt\n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query TaskDetail($id: ID!) {\n    getTask(id: $id) {\n      id\n      title\n      description\n      type\n      weight\n      progress\n      status\n      priority\n      dueDate\n      projectId\n      subtasks {\n        id\n        title\n        weight\n        isComplete\n      }\n      assignees {\n        id\n        userId\n        user {\n          id\n          fullName\n          email\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query TaskDetail($id: ID!) {\n    getTask(id: $id) {\n      id\n      title\n      description\n      type\n      weight\n      progress\n      status\n      priority\n      dueDate\n      projectId\n      subtasks {\n        id\n        title\n        weight\n        isComplete\n      }\n      assignees {\n        id\n        userId\n        user {\n          id\n          fullName\n          email\n        }\n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  mutation CreateTask(\n    $projectId: ID!\n    $title: String!\n    $description: String\n    $type: TaskTypeEnumType\n    $weight: Int!\n    $priority: TaskPriorityEnumType\n    $dueDate: DateTime\n  ) {\n    createTask(\n      projectId: $projectId\n      title: $title\n      description: $description\n      type: $type\n      weight: $weight\n      priority: $priority\n      dueDate: $dueDate\n    ) {\n      id\n    }\n  }\n"): (typeof documents)["\n  mutation CreateTask(\n    $projectId: ID!\n    $title: String!\n    $description: String\n    $type: TaskTypeEnumType\n    $weight: Int!\n    $priority: TaskPriorityEnumType\n    $dueDate: DateTime\n  ) {\n    createTask(\n      projectId: $projectId\n      title: $title\n      description: $description\n      type: $type\n      weight: $weight\n      priority: $priority\n      dueDate: $dueDate\n    ) {\n      id\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  mutation UpdateTask($id: ID!, $status: TaskStatusEnumType, $progress: Int) {\n    updateTask(id: $id, status: $status, progress: $progress) {\n      id\n      status\n      progress\n    }\n  }\n"): (typeof documents)["\n  mutation UpdateTask($id: ID!, $status: TaskStatusEnumType, $progress: Int) {\n    updateTask(id: $id, status: $status, progress: $progress) {\n      id\n      status\n      progress\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  mutation AddProjectMember($projectId: ID!, $memberUserId: ID!, $roleId: ID!) {\n    addProjectMember(projectId: $projectId, memberUserId: $memberUserId, roleId: $roleId) {\n      id\n    }\n  }\n"): (typeof documents)["\n  mutation AddProjectMember($projectId: ID!, $memberUserId: ID!, $roleId: ID!) {\n    addProjectMember(projectId: $projectId, memberUserId: $memberUserId, roleId: $roleId) {\n      id\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  mutation UpdateProject($id: ID!, $name: String, $description: String, $status: ProjectStatusEnumType) {\n    updateProject(id: $id, name: $name, description: $description, status: $status) {\n      id\n      name\n      description\n      status\n    }\n  }\n"): (typeof documents)["\n  mutation UpdateProject($id: ID!, $name: String, $description: String, $status: ProjectStatusEnumType) {\n    updateProject(id: $id, name: $name, description: $description, status: $status) {\n      id\n      name\n      description\n      status\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  mutation CreateSubtask($taskId: ID!, $title: String!, $weight: Int!) {\n    createSubtask(taskId: $taskId, title: $title, weight: $weight) {\n      id\n      subtasks {\n        id\n        title\n        weight\n        isComplete\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation CreateSubtask($taskId: ID!, $title: String!, $weight: Int!) {\n    createSubtask(taskId: $taskId, title: $title, weight: $weight) {\n      id\n      subtasks {\n        id\n        title\n        weight\n        isComplete\n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  mutation UpdateSubtask($id: ID!, $isComplete: Boolean, $weight: Int) {\n    updateSubtask(id: $id, isComplete: $isComplete, weight: $weight) {\n      id\n      subtasks {\n        id\n        title\n        weight\n        isComplete\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation UpdateSubtask($id: ID!, $isComplete: Boolean, $weight: Int) {\n    updateSubtask(id: $id, isComplete: $isComplete, weight: $weight) {\n      id\n      subtasks {\n        id\n        title\n        weight\n        isComplete\n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query ProjectRoles($limit: Int) {\n    getRoles(limit: $limit) {\n      nodes {\n        id\n        code\n        name\n      }\n    }\n  }\n"): (typeof documents)["\n  query ProjectRoles($limit: Int) {\n    getRoles(limit: $limit) {\n      nodes {\n        id\n        code\n        name\n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query ProjectUsers($limit: Int, $filters: UserFilterInputType) {\n    getUsers(limit: $limit, filters: $filters) {\n      nodes {\n        id\n        fullName\n        email\n      }\n    }\n  }\n"): (typeof documents)["\n  query ProjectUsers($limit: Int, $filters: UserFilterInputType) {\n    getUsers(limit: $limit, filters: $filters) {\n      nodes {\n        id\n        fullName\n        email\n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query Projects($page: Int, $limit: Int, $filters: ProjectFilterInputType) {\n    getProjects(page: $page, limit: $limit, filters: $filters) {\n      nodes {\n        id\n        name\n        description\n        status\n        progressPercent\n        memberCount\n        createdAt\n        updatedAt\n      }\n      pageInfo {\n        isFirstPage\n        isLastPage\n        currentPage\n        previousPage\n        nextPage\n        pageCount\n        totalCount\n      }\n    }\n  }\n"): (typeof documents)["\n  query Projects($page: Int, $limit: Int, $filters: ProjectFilterInputType) {\n    getProjects(page: $page, limit: $limit, filters: $filters) {\n      nodes {\n        id\n        name\n        description\n        status\n        progressPercent\n        memberCount\n        createdAt\n        updatedAt\n      }\n      pageInfo {\n        isFirstPage\n        isLastPage\n        currentPage\n        previousPage\n        nextPage\n        pageCount\n        totalCount\n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  mutation CreateProject($name: String!, $description: String) {\n    createProject(name: $name, description: $description) {\n      id\n      name\n    }\n  }\n"): (typeof documents)["\n  mutation CreateProject($name: String!, $description: String) {\n    createProject(name: $name, description: $description) {\n      id\n      name\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query Me {\n    me {\n      id\n      email\n      firstName\n      lastName\n      roleName\n      sessions {\n        nodes {\n          id\n          expiresAt\n          userAgent\n          ipAddress\n          revoked\n          revokedAt\n          createdAt\n        }\n        pageInfo {\n          totalCount\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query Me {\n    me {\n      id\n      email\n      firstName\n      lastName\n      roleName\n      sessions {\n        nodes {\n          id\n          expiresAt\n          userAgent\n          ipAddress\n          revoked\n          revokedAt\n          createdAt\n        }\n        pageInfo {\n          totalCount\n        }\n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  mutation UpdateUser($firstName: String, $lastName: String, $email: String) {\n    updateUser(firstName: $firstName, lastName: $lastName, email: $email) {\n      id\n    }\n  }\n"): (typeof documents)["\n  mutation UpdateUser($firstName: String, $lastName: String, $email: String) {\n    updateUser(firstName: $firstName, lastName: $lastName, email: $email) {\n      id\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  mutation CreateRole(\n    $name: String!\n    $code: String!\n    $description: String\n    $permissionCodes: [PermissionEnumType!]!\n  ) {\n    createRole(\n      name: $name\n      code: $code\n      description: $description\n      permissionCodes: $permissionCodes\n    ) {\n      id\n    }\n  }\n"): (typeof documents)["\n  mutation CreateRole(\n    $name: String!\n    $code: String!\n    $description: String\n    $permissionCodes: [PermissionEnumType!]!\n  ) {\n    createRole(\n      name: $name\n      code: $code\n      description: $description\n      permissionCodes: $permissionCodes\n    ) {\n      id\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query Role($id: ID!) {\n    getRole(id: $id) {\n      id\n      code\n      name\n      description\n      permissions\n    }\n  }\n"): (typeof documents)["\n  query Role($id: ID!) {\n    getRole(id: $id) {\n      id\n      code\n      name\n      description\n      permissions\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  mutation UpdateRole(\n    $id: ID!\n    $name: String\n    $description: String\n    $permissionCodes: [PermissionEnumType!]\n  ) {\n    updateRole(\n      id: $id\n      name: $name\n      description: $description\n      permissionCodes: $permissionCodes\n    ) {\n      id\n    }\n  }\n"): (typeof documents)["\n  mutation UpdateRole(\n    $id: ID!\n    $name: String\n    $description: String\n    $permissionCodes: [PermissionEnumType!]\n  ) {\n    updateRole(\n      id: $id\n      name: $name\n      description: $description\n      permissionCodes: $permissionCodes\n    ) {\n      id\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query Roles($page: Int, $limit: Int, $filters: RoleFilterInputType) {\n    getRoles(page: $page, limit: $limit, filters: $filters) {\n      nodes {\n        id\n        code\n        name\n        description\n        createdAt\n      }\n      pageInfo {\n        isFirstPage\n        isLastPage\n        currentPage\n        previousPage\n        nextPage\n        pageCount\n        totalCount\n      }\n    }\n  }\n"): (typeof documents)["\n  query Roles($page: Int, $limit: Int, $filters: RoleFilterInputType) {\n    getRoles(page: $page, limit: $limit, filters: $filters) {\n      nodes {\n        id\n        code\n        name\n        description\n        createdAt\n      }\n      pageInfo {\n        isFirstPage\n        isLastPage\n        currentPage\n        previousPage\n        nextPage\n        pageCount\n        totalCount\n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query Users($page: Int, $limit: Int, $filters: UserFilterInputType) {\n    getUsers(page: $page, limit: $limit, filters: $filters) {\n      nodes {\n        id\n        email\n        firstName\n        lastName\n        fullName\n        roleName\n        roleCode\n        isActive\n        createdAt\n      }\n      pageInfo {\n        isFirstPage\n        isLastPage\n        currentPage\n        previousPage\n        nextPage\n        pageCount\n        totalCount\n      }\n    }\n  }\n"): (typeof documents)["\n  query Users($page: Int, $limit: Int, $filters: UserFilterInputType) {\n    getUsers(page: $page, limit: $limit, filters: $filters) {\n      nodes {\n        id\n        email\n        firstName\n        lastName\n        fullName\n        roleName\n        roleCode\n        isActive\n        createdAt\n      }\n      pageInfo {\n        isFirstPage\n        isLastPage\n        currentPage\n        previousPage\n        nextPage\n        pageCount\n        totalCount\n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  mutation RefreshToken($refreshToken: String!) {\n    refreshToken(refreshToken: $refreshToken) {\n      accessToken\n      refreshToken\n    }\n  }\n"): (typeof documents)["\n  mutation RefreshToken($refreshToken: String!) {\n    refreshToken(refreshToken: $refreshToken) {\n      accessToken\n      refreshToken\n    }\n  }\n"];

export function gql(source: string) {
  return (documents as any)[source] ?? {};
}

export type DocumentType<TDocumentNode extends DocumentNode<any, any>> = TDocumentNode extends DocumentNode<  infer TType,  any>  ? TType  : never;